#config/meta.yml

meta_product_name: 'Compassion'
meta_title: "Compassion - Anonymous Chat For Those Who Are Suffering"
meta_description: "Too many people are suffering the effects of mental illness. Compassion connects those who are suffering with those who can help. Everyone needs a compassionate partner."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@Compassionchat"   # required for Twitter Cards